/* @pjs preload=
"img/bg.jpg,
img/cabbage.png,
img/title.jpg,
img/gameover.jpg,
img/startNormal.png,
img/startHovered.png,
img/restartNormal.png,
img/restartHovered.png,
img/groundhogDown.png,
img/groundhogIdle.png,
img/groundhogLeft.png,
img/groundhogRight.png,
img/life.png,
img/soil8x24.png,
img/soil0.png,
img/soil1.png,
img/soil2.png,
img/soil3.png,
img/soil4.png,
img/soil5.png,
img/stone1.png,
img/stone2.png,
img/soldier.png"; */